- name: déploiement de dockercoins sur cluster k8s
  hosts: master
  become: false
  gather_facts: false
  tasks:
  - name: Vérifier cluster k8s
    command: kubectl cluster-info
    register: k8sClusterOk
  - name: Copier manifest yml sur master
    copy:
     src: /tmp/dockercoins-k8s.yml
     dest: /tmp/dockercoins-k8s.yml 
  - name: deploy dockercoins
    command: kubectl apply -f /tmp/dockercoins-k8s.yml

